/**
 * Build the in-app engine bundle: src/browser/engine-entry.ts → web/engine.bundle.js.
 *
 *   node scripts/build-web.mjs        (or: npm run build:web)
 *
 * One self-contained, same-origin IIFE the plain-script client loads under the
 * page's `script-src 'self'` CSP — no external origins, no CDN. The committed
 * bundle means `npm run web` and the offline smoke need no build step; rerun
 * this whenever the shared engine (src/core, src/providers) changes.
 *
 * The Node-only Character-Card loader (src/core/cards/card.ts: node:dns/net/fs/
 * zlib for URL/file import) is reachable only through a DYNAMIC import in
 * bot.ts, which the in-app engine never takes (it injects an upload-only
 * importer). We stub that module at bundle time so no `node:` builtin is pulled
 * into the browser graph; upload-based import uses card-browser.ts instead.
 */
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

/** Replace the Node URL/file card loader with a browser-safe stub. */
const stubNodeCardLoader = {
  name: 'stub-node-card-loader',
  setup(b) {
    b.onResolve({ filter: /cards\/card\.js$/ }, () => ({ path: 'omnidm-stub-card', namespace: 'stub' }));
    b.onLoad({ filter: /.*/, namespace: 'stub' }, () => ({
      loader: 'js',
      contents:
        'export async function loadCard(){throw new Error("URL/file card import is unavailable in-app; upload a card file.");}',
    }));
  },
};

const result = await build({
  entryPoints: [path.join(root, 'src/browser/engine-entry.ts')],
  outfile: path.join(root, 'web/engine.bundle.js'),
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  legalComments: 'none',
  banner: { js: '/* OmniDM in-app engine — GENERATED by scripts/build-web.mjs. Do not edit by hand. */' },
  plugins: [stubNodeCardLoader],
  logLevel: 'info',
});

if (result.errors.length) process.exit(1);
console.log('✅ web/engine.bundle.js built');
